export const genres = [
  "speculative fiction",
  "science fiction",
  "hard science fiction",
  "soft science fiction",
  "cyberpunk",
  "steampunk",
  "dieselpunk",
  "space opera",
  "dystopian",
  "utopian",
  "post-apocalyptic",
  "time travel",
  "fantasy",
  "high fantasy",
  "epic fantasy",
  "low fantasy",
  "urban fantasy",
  "dark fantasy",
  "historical fantasy",
  "magical realism",
  "horror",
  "psychological horror",
  "supernatural horror",
  "gothic horror",
  "cosmic horror",
  "lovecraftian horror",
  "body horror",
  "slasher",
  "mystery",
  "crime",
  "detective fiction",
  "whodunit",
  "police procedural",
  "noir",
  "hardboiled",
  "thriller",
  "suspense",
  "psychological thriller",
  "action thriller",
  "legal thriller",
  "literary fiction",
  "contemporary fiction",
  "drama",
  "romance",
  "contemporary romance",
  "historical romance",
  "paranormal romance",
  "erotic romance",
  "romantic comedy",
  "chick lit",
  "psychological fiction",
  "family saga",
  "coming-of-age",
  "bildungsroman",
  "historical fiction",
  "historical adventure",
  "biographical novel",
  "adventure",
  "humor",
  "satire",
  "graphic novel",
  "young adult (ya)",
  "children's fiction",
  "western",
  "inspirational",
  "christian fiction",
  "military fiction",
  "spy fiction (espionage)",
  "political thriller",
  "techno-thriller",
  "other"
];